LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := main.c
#LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)
LOCAL_MODULE_TAGS := optional
LOCAL_SHARED_LIBRARIES := libcutils liblog
LOCAL_C_INCLUDES := $(TOP)/system/core/include
#LOCAL_USE_STD_GNU_CPP11 := true
#LOCAL_MODULE := properties_test
LOCAL_MODULE := libgetenv

#LOCAL_CFLAGS += -DFLAGS_STR="\"\n\TARGET_GLOBAL_CFLAGS=$(TARGET_GLOBAL_CFLAGS)\n\
TARGET_\$\(mode\)_CFLAGS=$(TARGET_thumb_CFLAGS)\n\
LOCAL_CFLAGS=$(LOCAL_CFLAGS)\""
LOCAL_CLANG := false

include $(BUILD_SHARED_LIBRARY)
