.globl cops_context_create
cops_context_create:
.globl cops_context_destroy
cops_context_destroy:
.globl cops_read_imei
cops_read_imei:
.globl cops_simlock_get_status
cops_simlock_get_status:
.globl cops_simlock_unlock
cops_simlock_unlock:
.globl cops_get_challenge
cops_get_challenge:
.globl cops_authenticate
cops_authenticate:
.globl cops_deauthenticate
cops_deauthenticate:
.globl cops_bind_properties
cops_bind_properties:
.globl cops_read_data
cops_read_data:
