typedef enum AUDIO_HAL_STATE {
	AUDIO_HAL_STATE_OFF = 0,
	AUDIO_HAL_STATE_ON = 1
} AUDIO_HAL_STATE;

typedef enum AUDIO_HAL_STATUS {
	AUDIO_HAL_STATUS_OK = 0,
	AUDIO_HAL_STATUS_ERROR = 1,
	AUDIO_HAL_STATUS_UNSUPPORTED = 2
} AUDIO_HAL_STATUS;

typedef enum AUDIO_HAL_TYPE {
	AUDIO_HAL_DIGITAL = 0,
	AUDIO_HAL_ANALOG = 1
} AUDIO_HAL_TYPE;

typedef enum audio_hal_channel {
	AUDIO_HAL_CHANNEL_SPEAKER = 0,
	AUDIO_HAL_CHANNEL_EARPIECE,
	AUDIO_HAL_CHANNEL_HSETOUT,
	AUDIO_HAL_CHANNEL_HSETIN,
	AUDIO_HAL_CHANNEL_MIC,
	AUDIO_HAL_CHANNEL_FMTX,
	AUDIO_HAL_CHANNEL_FMRX,
	AUDIO_HAL_CHANNEL_BTOUT,
	AUDIO_HAL_CHANNEL_BTIN,
	AUDIO_HAL_CHANNEL_A2DPOUT, // Not used
	AUDIO_HAL_CHANNEL_VIBRAL,
	AUDIO_HAL_CHANNEL_VIBRAR,
	AUDIO_HAL_CHANNEL_HDMI, // Not used
	AUDIO_HAL_CHANNEL_TTYOUT, // Not used
	AUDIO_HAL_CHANNEL_TTYIN, // Not used
	AUDIO_HAL_CHANNEL_VOICE_DL, // Modem direct connection DownLink
	AUDIO_HAL_CHANNEL_VOICE_UL, // Modem direct connection UpLink
	AUDIO_HAL_CHANNEL_PDMOUT,
	AUDIO_HAL_CHANNEL_DIGMIC12,
	AUDIO_HAL_CHANNEL_DIGMIC34,
	AUDIO_HAL_CHANNEL_DIGMIC56,
} audio_hal_channel;
